name: Feeds
options:
  bundleIdPrefix: co.za.eoitech
  deploymentTarget:
    iOS: "17.0"
    macOS: "14.0"
settings:
  SWIFT_VERSION: "6.0"
  GENERATE_INFOPLIST_FILE: true
targets:
  Feeds:
    type: application
    platform: iOS
    sources:
      - path: Sources/Feeds
        excludes:
          - Resources/**
      - path: Sources/Feeds/Resources
        buildPhase: resources
    settings:
      INFOPLIST_KEY_UILaunchScreen_Generation: true
      INFOPLIST_KEY_CFBundleDisplayName: feeds
      INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.news"
      INFOPLIST_KEY_UIStatusBarStyle: ""
      INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown
      ASSETCATALOG_COMPILER_INCLUDE_ALL_APPICON_ASSETS: true
      CURRENT_PROJECT_VERSION: 1
      MARKETING_VERSION: 0.1.0
      PRODUCT_BUNDLE_IDENTIFIER: co.za.eoitech.feeds
      SWIFT_STRICT_CONCURRENCY: complete
      CODE_SIGN_STYLE: Automatic
      CODE_SIGN_IDENTITY: "Apple Development"
      DEVELOPMENT_TEAM: 53WGMXN227
  FeedsTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests/FeedsTests
    dependencies:
      - target: Feeds
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: co.za.eoitech.feedstests
      DEVELOPMENT_TEAM: 53WGMXN227
